import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryColumn,
} from 'typeorm';
import { UsersEntity } from './users.entity';

/**
 * Ledger table.
 *
 * - `id` is generated by the frontend (IK) and is the transaction identifier.
 * - `amount` is a signed integer in **cents** (can be positive or negative).
 */
@Entity({ name: 'transactions' })
@Index(['userId', 'ts'])
export class TransactionEntity {
  /** Frontend-generated idempotency key (IK). */
  @PrimaryColumn()
  id: string;

  @Column({ type: 'int', name: 'user_id' })
  userId: number;

  /** Signed amount in cents. */
  @Column({ type: 'bigint' })
  amount: string;

  @CreateDateColumn({ type: 'timestamptz', name: 'ts' })
  ts: Date;

  @ManyToOne(() => UsersEntity)
  @JoinColumn({ name: 'user_id' })
  user: UsersEntity;
}
